[versions]
agp = "8.13.2"
android = "2.13.0"
kotlin = "2.2.0"
coreKtx = "1.17.0"
# ksp
ksp = "2.2.0-2.0.2"
#Room
room = "2.7.2"

#Coil
coil = "2.7.0"
coilCompose = "3.3.0"
coilNetworkOkhttp = "3.3.0"

# DataStore
datastore = "1.1.1" # 최신 안정화 버전

#test tools
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"

#compose
composeBom = "2025.12.01"
activityCompose = "1.12.2"
appcompat = "1.7.1"
lifecycleRuntimeKtx = "2.10.0"
loggingInterceptor = "5.3.2"
material = "1.13.0"
jetbrainsKotlinJvm = "2.2.0"
navigationCompose = "2.9.6"
coroutines = "1.10.2"
hilt = "2.57.2"
hiltExt = "1.3.0"
javaxInject = "1"

kotlinxSerializationJson = "1.9.0"
materialIconsExtended = "1.7.8"

#Compose Map & Fused Location
mapsCompose = "6.12.2"
playServicesMaps = "19.2.0"
playServicesLocation = "21.3.0"
googleGmsServices = "4.4.4"

secretsGradlePlugin = "2.0.1"
v2All = "2.20.1"
v2User = "2.23.0"
kakaoMaps = "2.13.0"
retrofit = "2.11.0"
converterMoshi = "2.11.0"
moshiKotlin = "1.15.2"
okhttp = "4.12.0"
moshiCodegen = "1.15.2"

#compose firebase
firebaseBom = "34.7.0"
firebaseFirestoreKtx = "25.1.4"

[libraries]
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation"}
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }

#xml 기반 관리용
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

#compose version 관리용
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }

androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "materialIconsExtended" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
javax-inject = { group = "javax.inject", name = "javax.inject", version.ref = "javaxInject" }

androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

# Google Compose Maps & Fused Location Provider
maps-compose = { group = "com.google.maps.android", name = "maps-compose", version.ref = "mapsCompose" }
play-services-maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "playServicesMaps" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocation" }

#Kakao
v2-all = { module = "com.kakao.sdk:v2-all", version.ref = "v2All" }
v2-user = { group = "com.kakao.sdk", name = "v2-user", version.ref = "v2User" }
kakao-maps = { group = "com.kakao.maps.open", name = "android", version.ref = "kakaoMaps" }

retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
converter-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "converterMoshi" }
moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshiKotlin" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
moshi-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshiCodegen" }

#Firestore
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-firestore-ktx = { group = "com.google.firebase", name = "firebase-firestore-ktx", version.ref = "firebaseFirestoreKtx" }

#Room-DB
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }

#DataStore
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }

# Hilt core
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }

# Hilt + AndroidX
androidx-hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hiltExt" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltExt" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin"}
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin"}
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsServices" }
secrets-gradle-plugin = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin",  version.ref = "secretsGradlePlugin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[bundles]
compose-libraries=[
    "androidx-activity-compose",
    "androidx-compose-material3",
    "androidx-lifecycle-runtime-ktx",
    "androidx-compose-ui",
    "androidx-compose-ui-graphics",
    "androidx-compose-ui-tooling",
    "androidx-compose-ui-tooling-preview",
    "androidx-navigation-compose",
    "androidx-compose-material-icons-extended",
    "androidx-compose-foundation",
    "coil-compose",
]

coroutines = [
    "kotlinx-coroutines-core",
    "kotlinx-coroutines-android"
]

retrofits = [
    "moshi-kotlin",
    "retrofit",
    "converter-moshi",
]

okhttps = [
    "okhttp",
    "logging-interceptor"
]

room-libraries = [
    "androidx-room-ktx",
    "androidx-room-runtime"
]